default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['db_host'] || 'postgres' %>
  user: <%= ENV['db_user'] || 'root' %>
  password: <%= ENV['db_pass'] %>

development:
  <<: *default
  database: find_my_coffee_development

test:
  <<: *default
  database: find_my_coffee_test

production:
  <<: *default
  database: find_my_coffee_production
